language: python
python:
  - "3.4.5"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
    - apt-get install libdb5.3 libdb-dev
    - pip install -r requirements.txt
    - pip install https://github.com/Capitains/MyCapytain/archive/classmethod-for-parsing.zip --upgrade
    - pip install https://github.com/PonteIneptique/rdflib-sqlalchemy/archive/empty-prefix-fix.zip --upgrade
    - pip install coveralls

# command to run tests
script:
    - coverage run --source=capitains_nautilus setup.py test

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then coveralls; fi

branches:
  only:
    - master
    - documentation
    - sparql-collections
    - sparql-collection-multiproc
    - dev
    - sparql-optimization


deploy:
  provider: pypi
  user: ponteineptique
  password: $PYPASS
  on:
    tags: true
    python: "3.5"