language: python
python:
  - "3.4.5"
  - "3.5"
  - "3.6"

services:
  - "redis"

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls

# command to run tests
script:
    - coverage run --source=capitains_nautilus setup.py test

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then coveralls; fi

branches:
  only:
    - master
    - documentation


deploy:
  provider: pypi
  user: ponteineptique
  password: $PYPASS
  on:
    tags: true
    python: "3.5"